### ISSUE TITLE
Building the wheel doesn't work

### ISSUE THREAD

**Issue by papoteur-mga** [mozilla/django-csp#188] opened 2022-10-29 08:07 UTC
Hello,
The module was packaged for Mageia since a while.
But with the current django version, the build fails:

```
running egg_info
writing django_csp.egg-info/PKG-INFO
writing dependency_links to django_csp.egg-info/dependency_links.txt
writing requirements to django_csp.egg-info/requires.txt
writing top-level names to django_csp.egg-info/top_level.txt
reading manifest file 'django_csp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'django_csp.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/home/pterjan/rpmbuild/BUILD/django_csp-3.7/setup.py", line 46, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 224, in run
    self.run_tests()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 227, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 57, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.10/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 57, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pterjan/rpmbuild/BUILD/django_csp-3.7/csp/tests/test_jinja_extension.py", line 1, in <module>
    from csp.tests.utils import ScriptExtensionTestBase
  File "/home/pterjan/rpmbuild/BUILD/django_csp-3.7/csp/tests/utils.py", line 8, in <module>
    mw = CSPMiddleware()
TypeError: MiddlewareMixin.__init__() missing 1 required positional argument: 'get_response'
```
Django version: 4.1.2

**Comment by some1ataplace** [comment] 2023-03-24 17:23
To enable CI to run for pull requests on the django-csp repository, you will need to configure the repository settings on the CI platform you are using. Here are the general steps to follow:

1. Determine which CI platform the django-csp repository is using. It could be Travis CI, CircleCI, GitHub Actions, or another platform.

2. Check the repository settings on the CI platform to see if pull request builds are enabled. If they are not enabled, enable them.

3. If pull request builds are already enabled, check the configuration file for the CI build to ensure that it is configured to run on pull requests. For example, on Travis CI, you would need to add the following code to your .travis.yml file:
```

# .travis.yml
branches:
  only:
    - master
    - /^pull\/.*$/
```

This configuration tells Travis CI to run builds on the master branch and any pull request branches (/^pull\/.*$/).

***

To troubleshoot issues with building the wheel for django-csp, you can try the following steps:

1. Make sure you have the latest version of setuptools and wheel installed:

pip install --upgrade setuptools wheel


2. Check that you have all the required dependencies installed. You can do this by running:

pip install -r requirements.txt


3. Try building the wheel again with the following command:

python setup.py bdist_wheel


4. If you still encounter errors, check the error message for any specific issues and search for solutions online. You can also try building the wheel in a clean virtual environment to rule out any conflicts with other packages.


***

Based on the traceback you provided, it seems that the error is caused by a missing dependency. Specifically, the cffi module is not found.

To fix this issue, you can try installing the cffi module manually using the following command:

`pip install cffi`


Once you have installed cffi, try building the wheel again with the following command:

`python setup.py bdist_wheel`


If you still encounter errors, check the error message for any specific issues and search for solutions online. You can also try building the wheel in a clean virtual environment to rule out any conflicts with other packages.

**Comment by stevejalim** [comment] 2024-01-26 10:41
@papoteur-mga Hello! Sorry for the long wait on this one. `main` is now [building against recent Django and Python versions](https://github.com/mozilla/django-csp/actions/runs/7660909884). Could you confirm whether you can now build a wheel?

I'd like to get a 3.8rc out of the door soon, followed by a formal 3.8 with very few/zero functional changes, mostly just Python and Django support.

**Comment by papoteur-mga** [comment] 2024-01-26 11:30
@stevejalim 
We have been able to build the version from a snapshot at tag 17d941543e9acbf4a51cd3f2393ead458034995d
Thanks

**Comment by stevejalim** [comment] 2024-01-26 12:43
OK thanks @papoteur-mga - I'll close this Issue, but feel free to re-open if you hit packaging issues with the new 3.8 release when it lands

**Closed** 2024-01-26 12:43 UTC
